"""
ReportWriterTool — formats analysis results into a clean Markdown report.
"""
from datetime import datetime
from pydantic import BaseModel, Field

from app.tools.base import LoggedTool


class ReportWriterInput(BaseModel):
    title: str = Field(description="Report title")
    content: str = Field(description="Main content/findings to include in the report")
    report_type: str = Field(
        default="general",
        description="Type: 'general', 'analytics', 'incident', 'review'",
    )


class ReportWriterTool(LoggedTool):
    name: str = "ReportWriter"
    description: str = (
        "Format analysis results into a structured Markdown report. "
        "Provide a title, content/findings, and report type. "
        "report_type options: general, analytics, incident, review"
    )
    args_schema: type[BaseModel] = ReportWriterInput

    def _run(self, title: str, content: str, report_type: str = "general") -> str:
        now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        type_headers = {
            "analytics": "📊 Analytics Report",
            "incident": "🚨 Incident Report",
            "review": "🔍 Review Report",
            "general": "📋 Report",
        }
        header_label = type_headers.get(report_type, "📋 Report")

        report = f"""# {header_label}: {title}

**Generated:** {now}
**Type:** {report_type.capitalize()}

---

## Summary

{content}

---

*Report generated by IT Company AI Platform*
"""
        return report
